version: '1'

services:
  database:
    image: postgres
    container_name: books_db
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgressql

volumes:
  database:
